eerste_dure_woorden = [
    "Accuraat: nauwkeurig.",
    "Mogendheid: soevereine staat: de grote mogendheden.",
    "Apocrief: ongeloofwaardig.",
    "Concubinaat: buitenechtelijke samenleving.",
    "Peigeren: doodgaan, sterven.",
    "Burgerlijk: eenvoudig als een burger; (ook negatief) kleingeestig, bekrompen.",
    "Faillissement: toestand van een schuldenaar die niet in staat is aan zijn verplichtingen te voldoen, terwijl gerechtelijk beslag gelegd is op het hele vermogen.",
    "Vacature: openstaande functie.",
    "Flagrant: overduidelijk, onloochenbaar: een flagrante schending van de mensenrechten.",
    "Accommodatie: aangebrachte voorzieningen.",
    "Netelig: lastig, moeilijk, hachelijk.",
    "Vitaal: voor het leven van groot belang.",
    "Utopie: onbereikbaar ideaal.",
    "Fraude: bedrog, gepleegd door vervalsing van administratie.",
    "Louche: onguur; = onbetrouwbaar.",
    "Rato: naar rato naar evenredigheid.",
    "Optornen: tegen iets optornen er met moeite tegen ingaan.",
    "Intern: inwendig, van binnen.",
    "Fatale: noodlottig; de dood tot gevolg hebbend.",
    "Ratio: verhouding.",
    "Distantiëren: afstand nemen van een mening.",
    "Euthanasie: letterlijk betekenis: zachte dood. Iemand op zijn of haar verzoek pijnloos doden wegens een ongeneeslijke ziekte die ondraaglijk lijden met zich meebrengt.",
    "Karekiet: bruine zangvogel.",
    "Weifelen: onzeker zijn over de beslissing die gekozen moet worden.",
    "Accelereren: het sneller laten gaan.",
    "Appreciëren:  beschouwen als waardevol.",
    "Eega: een eega kan zowel een man als een vrouw zijn: het woord betekent dus 'echtgenoot' én 'echtgenote'. Het is dus niet juist om eega alleen voor een vrouw te gebruiken en ega voor een man. De spelling ega is niet juist.",
    "Gynaecoloog: de gynaecoloog houdt zich onder meer bezig met afwijkingen en ziekten van de vrouwelijke geslachtsorganen: infecties en ontstekingen, kanker, verzakkingsproblemen, incontinentie, hormonale problemen met of zonder menstruatiecyclus afwijkingen, seksuele problemen.",
    "Onbedaarlijk: niet in staat om tot bedaren te komen.",
    "Onmiskenbaar: onloochenbaar; niet te ontkennen",
    "Prevelde: zacht binnensmonds zeggen.",
    "Tumult: het lawaai zoals veroorzaakt door een menigte.",
    "Gezworene: ander woord voor jurylid.",
    "Slaken: uiten.",
    "Hachelijk: gevaarlijk, gewaagd.",
    "Tomeloos: onbedwongen, teugelloos.",
    "Uitstaand: nog te betalen.",
    "Geëscaleerd: uit de hand gelopen"
]
